export const CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
};

export const DEFAULT_BASE_CURRENCY = CURRENCIES.USD;

export const DEFAULT_COMPARISON_CURRENCIES = [CURRENCIES.EUR, CURRENCIES.GBP];
